### ISSUE TITLE
Question about the HyDRA pipeline

### ISSUE THREAD

**Issue by philiptzou** [phac-nml/quasitools#1]
Hello,

Greetings! First of all I'd like to thank you for developing such a useful pipeline of processing NGS sequences.

Here I have a fews questions about the HyDRA pipeline:

1. In [`cmd_hydra.py#L92`](https://github.com/phac-nml/quasitools/blob/4a20351/quasitools/commands/cmd_hydra.py#L92), why combined the forward and backward sequences together but not to align them in pairs by `bowtie2` (the `-1` and `-2` options)?
2. What's the reason(s) for [filtering FASTQ file(s)](https://github.com/phac-nml/quasitools/blob/4a20351/quasitools/commands/cmd_hydra.py#L116) before but not after the alignment?
3. What's the rationales for these options for `bowtie2` in [`patient_analyzer.py`](https://github.com/hivdb/quasitools/blob/4a2035/quasitools/patient_analyzer.py#L211):
    - `--rdg 8,3` and `--rfg 8,3`: changed the gap opening penalty from default 5 to 8.
    - `--ma 1`: changed the match bonus from default 2 to 1.
    - `--mp '2,2'`: ignored the affect of phred quality score during the alignment.

Thanks for your attention. I’m looking forward to your reply.

Best,
Philip

**Comment by ericenns** [comment]
> 1. In cmd_hydra.py#L92, why combined the forward and backward sequences together but not to align them in pairs by bowtie2 (the -1 and -2 options)?

Aligning reads as pairs is highly dependent on the sequencing protocol, whereas combining the read sets and aligning as single end will work for any sequencing protocol. By this I mean if you perform size selection you can set the min (`-I`) and max (`-x`) insert size and bowtie2 will flag the alignments that are outside the range. But if you do not perform size selection, you would have to set the min (`-I`) and max (`-x`) insert size to a large range so that it doesn't flag any of the alignments. Additionally we do not filter out forward and reverse reads together, which we would need to do if aligning as pairs.

> 2. What's the reason(s) for filtering sam/bam file(s) before but not after the alignment?

To reduce our input size prior to alignment. Originally we were filtering on percent identity and percent similarity post alignment, but it was removed as it didn't add any value as bowtie2 was already flagging those alignments.

> 3. What's the rationales for these options for bowtie2 in patient_analyzer.py:
--rdg 8,3 and --rfg 8,3: changed the read gap opening penalty from default 5 to 8.
--ma 1: changed the march bonus from default 2 to 1.
--mp '2,2': ignored the affect of phred quality score during the alignment.

These parameters were modified from the default to prioritize aligning gaps together. I basically ran a pen and paper simulation to achieve the optimal alignment around homopolymers.

**Comment by philiptzou** [comment]
Dear Eric,

Thanks for the answers! It's really helpful.

Philip
